# Generated by Django 3.2.15 on 2022-11-06 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('ap_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('rut', models.CharField(max_length=8, verbose_name='RUT')),
                ('dv', models.CharField(max_length=1, verbose_name='Dv')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo electronico')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('usuario_superAdministrador', models.BooleanField(default=False)),
                ('usuario_admin', models.BooleanField(default=False)),
                ('usuario_cliente', models.BooleanField(default=True)),
                ('usuario_funcionario', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('annio_experiencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.comuna')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleDpto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveBigIntegerField(default=0)),
                ('capacidad', models.IntegerField()),
                ('amoblado', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('cable', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('electronicos', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('internet', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('aire_acondicionado', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('bodega', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('bannio', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('cant_bannio', models.PositiveIntegerField(default=0)),
                ('dormitorio', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('cant_dormitorio', models.PositiveIntegerField(default=0)),
                ('estacionamiento', models.CharField(choices=[('se', 'Seleccione'), ('SI', 'SI'), ('NO', 'NO')], default='se', max_length=2)),
                ('cant_estacionamiento', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('0', 'Seleccione'), ('1', 'Disponible'), ('2', 'Mantencion'), ('3', 'No Disponible')], default='0', max_length=13)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='home.departamento')),
            ],
            options={
                'verbose_name': 'Detalle departamento',
                'verbose_name_plural': 'Detalles de Departamentos',
                'db_table': 'detalle_dpto',
            },
        ),
        migrations.CreateModel(
            name='DetalleTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_tp', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_in', models.TimeField(blank=True, default='00:00', null=True)),
                ('horario_fin', models.TimeField(blank=True, default='00:00', null=True)),
                ('costo_tp', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Detalle Transporte',
                'verbose_name_plural': 'Detalle de Transportes',
                'db_table': 'detalleTP',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTour', models.CharField(blank=True, choices=[('0', 'Seleccione'), ('1', 'Turismo Cultural'), ('2', 'Turismo de Naturaleza'), ('3', 'Turismo Gastronomico')], default='0', max_length=100, null=True)),
                ('nombreTour', models.CharField(blank=True, max_length=200, null=True)),
                ('horario_in', models.TimeField(blank=True, default='00:00', null=True)),
                ('horario_fin', models.TimeField(blank=True, default='00:00', null=True)),
                ('costo', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(blank=True, max_length=6, null=True)),
                ('tipo_transporte', models.CharField(blank=True, choices=[('0', 'Seleccione'), ('1', 'Taxi'), ('2', 'Furgoneta'), ('3', 'Bus')], default='0', max_length=30, null=True)),
                ('annio', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('num_puertas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kmRecorridos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conductor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.modelo')),
            ],
            options={
                'verbose_name': 'Trasporte',
                'verbose_name_plural': 'Trasportes',
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('booking_id', models.CharField(default='null', max_length=100)),
                ('cant_dias_reserva', models.IntegerField(default=0)),
                ('total_reserva', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Activa'), ('2', 'Cancelada')], default='1', max_length=12)),
                ('status_estadia', models.CharField(choices=[('0', 'Seleccionar'), ('1', 'Arribo'), ('2', 'No Arribo')], default='0', max_length=13)),
                ('mensaje_check_in', models.TextField(blank=True)),
                ('mensaje_check_out', models.TextField(blank=True)),
                ('costo_multa', models.IntegerField(default=0)),
                ('detalle_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.detalledpto')),
                ('detalle_tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.detalletp')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tour')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='../static/default/default.png', upload_to='departamentos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='home.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='detalletp',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transporte'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.region'),
        ),
    ]
