# Generated by Django 3.2.15 on 2022-11-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledpto',
            name='cant_dias_mantencion',
            field=models.IntegerField(default=0),
        ),
    ]
