# Generated by Django 3.2.15 on 2022-10-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_administrador',
            new_name='usuario_superAdministrador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_funcionario',
            field=models.BooleanField(default=False),
        ),
    ]
