# Generated by Django 3.2.15 on 2022-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletp',
            name='lugar_tp',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
