# Generated by Django 3.2.15 on 2022-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='img',
            field=models.ImageField(default='../static/default/default.png', upload_to='comunas'),
        ),
    ]
