# Generated by Django 3.2.15 on 2022-11-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_detalledpto_cant_dias_mantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='huespedes',
            field=models.IntegerField(default=0),
        ),
    ]
