# Generated by Django 3.2.15 on 2022-11-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reserva_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='detalle_tp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.detalletp'),
        ),
    ]
