# Generated by Django 3.2.15 on 2022-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reserva_costo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='status',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=13),
        ),
    ]
