# Generated by Django 3.2.15 on 2022-11-23 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221121_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='detalle_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleDpto', to='home.detalledpto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('1', 'Activa'), ('2', 'Cancelada'), ('3', 'Terminada'), ('4', 'En Proceso')], default='1', max_length=12),
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_ws', models.CharField(default='0', max_length=255)),
                ('tarjeta', models.CharField(default='0', max_length=10)),
                ('fecha_transbank', models.CharField(default='0', max_length=100)),
                ('estado_transbank', models.CharField(default='0', max_length=100)),
                ('total', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.reserva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order de Reserva',
                'verbose_name_plural': 'Ordenes de Reservas',
                'db_table': 'orden_de_reserva',
            },
        ),
    ]
