# Generated by Django 3.2.15 on 2022-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('1', 'Activa'), ('2', 'Cancelada')], default='1', max_length=12),
        ),
    ]
