# Generated by Django 3.2.15 on 2022-11-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_transporte_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledpto',
            name='status',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Mantencion'), ('3', 'No Disponible')], default='1', max_length=13),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='home.marca'),
        ),
    ]
