# Generated by Django 3.2.15 on 2022-10-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_detalledpto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='../static/default/default.png', upload_to='departamentos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
            ],
        ),
    ]
