# Generated by Django 3.2.15 on 2022-11-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221123_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletp',
            name='status',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], default='1', max_length=12),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], default='1', max_length=13),
        ),
    ]
