# Generated by Django 3.2.15 on 2022-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comuna_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_reserva',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
