# Generated by Django 3.2.15 on 2022-11-07 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reserva_huespedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledpto',
            name='fin_mantencion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='detalledpto',
            name='inicio_mantencion',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
