# Generated by Django 3.2.15 on 2022-11-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221110_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporte',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Trasportes'},
        ),
    ]
