# Generated by Django 3.2.15 on 2022-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_reserva_detalle_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='comuna',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
