# Generated by Django 3.2.15 on 2022-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reserva_total_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='total_reserva',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
