# Generated by Django 3.2.15 on 2022-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_transporte_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='status',
            field=models.CharField(choices=[('1', 'Activa'), ('2', 'Cancelada')], default='1', max_length=12),
        ),
    ]
