# Generated by Django 3.2.15 on 2022-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transporte_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='status',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=12),
        ),
    ]
