# Generated by Django 3.2.15 on 2022-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reserva_total_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cant_dias_reserva',
            field=models.IntegerField(default=0),
        ),
    ]
