# Generated by Django 3.2.15 on 2022-10-17 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reserva_cant_dias_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
